all_joints:
- - 0
- - 1
- - 2
- - 3
- - 4
- - 5
- - 6
all_joints_names:
- White
- Pink
- Yellow
- Orange
- Green
- Blue
- Red
alpha_r: 0.02
apply_prob: 0.5
batch_size: 1
contrast:
  clahe: true
  claheratio: 0.1
  histeq: true
  histeqratio: 0.1
convolution:
  edge: false
  emboss:
    alpha:
    - 0.0
    - 1.0
    strength:
    - 0.5
    - 1.5
  embossratio: 0.1
  sharpen: false
  sharpenratio: 0.3
cropratio: 0.4
dataset: training-datasets/iteration-0/UnaugmentedDataSet_7Bugs2SegmentsAug13/7Bugs2Segments_Yuva95shuffle1.mat
dataset_type: imgaug
decay_steps: 30000
display_iters: 1000
global_scale: 0.8
init_weights: /usr/local/lib/python3.10/dist-packages/deeplabcut/pose_estimation_tensorflow/models/pretrained/resnet_v1_50.ckpt
intermediate_supervision: false
intermediate_supervision_layer: 12
location_refinement: true
locref_huber_loss: true
locref_loss_weight: 0.05
locref_stdev: 7.2801
lr_init: 0.0005
max_input_size: 1500
metadataset: training-datasets/iteration-0/UnaugmentedDataSet_7Bugs2SegmentsAug13/Documentation_data-7Bugs2Segments_95shuffle1.pickle
min_input_size: 64
mirror: false
multi_stage: false
multi_step:
- - 0.005
  - 10000
- - 0.02
  - 430000
- - 0.002
  - 730000
- - 0.001
  - 1030000
net_type: resnet_50
num_joints: 7
pairwise_huber_loss: false
pairwise_predict: false
partaffinityfield_predict: false
pos_dist_thresh: 17
project_path: /content/drive/My Drive/Colab Notebooks/Summer24Notebooks/forVideos/DEEPCUT/7Bugs2Segments-Yuva-2024-08-13
rotation: 25
rotratio: 0.4
save_iters: 50000
scale_jitter_lo: 0.5
scale_jitter_up: 1.25
